apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terraformer.fullname" . }}
  labels:
    {{- include "terraformer.labels" . | nindent 4 }}
data:
  terraform.tfvars: |
    {{- toYaml .Values.tfvalues | nindent 8 }}
